"""Create Game and Review tables

Revision ID: 47cad843deb5
Revises: 23cd5143c79d
Create Date: 2023-10-08 21:52:13.927418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47cad843deb5'
down_revision = '23cd5143c79d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
